# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        # stages: [push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        exclude: build_helpers
        additional_dependencies:
          - types-cachetools==5.3.0.5
          - types-filelock==3.2.7
          - types-requests==2.31.0.1
          - types-tabulate==0.9.0.2
          - types-python-dateutil==2.8.19.13
          - SQLAlchemy==2.0.16
        # stages: [push]

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)
        # stages: [push]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.270'
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                tests/.*|
                .*\.svg|
                .*\.yml|
                .*\.json
            )$
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-ast
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .*\.md
            )$
