site_name: Freqtrade
site_url: https://www.freqtrade.io/
repo_url: https://github.com/freqtrade/freqtrade
use_directory_urls: True
nav:
    - Home: index.md
    - Quickstart with Docker: docker_quickstart.md
    - Installation:
        - Linux/MacOS/Raspberry: installation.md
        - Windows: windows_installation.md
    - Freqtrade Basics: bot-basics.md
    - Configuration: configuration.md
    - Strategy Customization: strategy-customization.md
    - Plugins: plugins.md
    - Stoploss: stoploss.md
    - Start the bot: bot-usage.md
    - Control the bot:
        - Telegram: telegram-usage.md
        - REST API & FreqUI: rest-api.md
        - Web Hook: webhook-config.md
    - Data Downloading: data-download.md
    - Backtesting: backtesting.md
    - Hyperopt: hyperopt.md
    - Utility Sub-commands: utils.md
    - Plotting: plotting.md
    - Exchange-specific Notes: exchanges.md
    - Data Analysis:
        - Jupyter Notebooks: data-analysis.md
        - Strategy analysis: strategy_analysis_example.md
    - Advanced Topics:
        - Advanced Post-installation Tasks: advanced-setup.md
        - Edge Positioning: edge.md
        - Advanced Strategy: strategy-advanced.md
        - Advanced Hyperopt: advanced-hyperopt.md
        - Sandbox Testing: sandbox-testing.md
    - FAQ: faq.md
    - SQL Cheat-sheet: sql_cheatsheet.md
    - Updating Freqtrade: updating.md
    - Deprecated Features: deprecated.md
    - Contributors Guide: developer.md
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  custom_dir: 'docs/overrides'
  palette:
    - scheme: default
      primary: 'blue grey'
      accent: 'tear'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'blue grey'
      accent: 'tear'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - 'stylesheets/ft.extra.css'
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
