---
version: '3'
services:
  ft_jupyterlab:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter
    restart: unless-stopped
    # container_name: freqtrade
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "../user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      jupyter lab --port=8888 --ip 0.0.0.0 --allow-root
