name: Devcontainer Pre-Build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "master"
  #   tags:
  #     - "v*.*.*"
  #   pull_requests:
  #     branches:
  #       - "master"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    -
        name: Pre-build dev container image
        uses: devcontainers/ci@v0.2
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: always
